### ISSUE TITLE
Move distribution account loading into application startup function

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#334]
I upgraded to Polaris v1.1.1 and migrated the database. Then, when creating the first asset in the database I got this:
```
Traceback (most recent call last):
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: polaris_asset.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/yuri/work/polaris-anchor/app/management/commands/create_asset.py", line 70, in handle
    asset = Asset.objects.create(
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/yuri/.virtualenvs/polaris_venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: polaris_asset.id
```

This error never happened before Polaris v1.1.1, and I imagine it's related to this [new Polaris code in the Asset model](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/models.py#L120):
```
class Asset(TimeStampedModel):
    def __init__(self, *args, **kwargs):
        """
        Does the usual __init__() actions and ensures the asset's distribution account
        information is up-to-date if it hasn't been pulled from Horizon since
        application starup.
        """
        super().__init__(*args, **kwargs)
        this = sys.modules[__name__]
        if str(self) not in this.ASSET_DISTRIBUTION_ACCOUNT_LOADED:
            update_distribution_account_data(self)  #  <- this runs .save() and might be the cause of the error
            this.ASSET_DISTRIBUTION_ACCOUNT_LOADED[str(self)] = True
```

**Comment by JakeUrban** [comment]
There are other issues that are related to the `Asset.__init__()` changes introduced in 1.1.1. I may need to release 1.1.2 with a different approach to loading assets' distribution accounts.

**Comment by JakeUrban** [comment]
While making queries to the database from `AppConfig.ready()` is [discouraged](https://docs.djangoproject.com/en/2.2/ref/applications/#django.apps.AppConfig.ready), I believe I can limit the circumstances in which `.ready()` makes API calls and DB queries, negating the potential issues.

We'll move the loading code from `Asset.__init__()` to `AppConfig.ready()` and ensure distribution accounts are only loaded when running processes that need them refreshed.

**Comment by yuriescl** [comment]
@JakeUrban Why not turn them into properties and load when they're called? This would remove any need for loading on startup.

**Comment by yuriescl** [comment]
I don't think `save()` is needed there since it's loaded every time the process starts.

**Comment by JakeUrban** [comment]
Great idea, I don't know why I didn't think of that.
