### ISSUE TITLE
calculate_fee unsupported operand types Decimal and float

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#338]
Getting this error when running `poll_pending_deposits`:
```
$ python manage.py poll_pending_deposits
polaris.apps: SECURE_SSL_REDIRECT is required to redirect HTTP traffic to HTTPS
polaris.apps: SECURE_PROXY_SSL_HEADER should only be set if Polaris is running behind an HTTPS reverse proxy.
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/yuri/.virtualenvs/polaris/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/yuri/.virtualenvs/polaris/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/yuri/.virtualenvs/polaris/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/yuri/.virtualenvs/polaris/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/yuri/.virtualenvs/polaris/lib/python3.8/site-packages/polaris/management/commands/poll_pending_deposits.py", line 135, in handle
    self.execute_deposits()
  File "/home/yuri/.virtualenvs/polaris/lib/python3.8/site-packages/polaris/management/commands/poll_pending_deposits.py", line 169, in execute_deposits
    transaction.amount_fee = calculate_fee(
  File "/home/yuri/.virtualenvs/polaris/lib/python3.8/site-packages/polaris/integrations/fees.py", line 50, in calculate_fee
    fee_fixed + (fee_percent / Decimal("100") * amount), asset.significant_decimals,
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
```

This happens because I set `transaction.amount_in` and it isn't automatically converted to `Decimal` when Polaris calls `calculate_fee()`.

**Comment by JakeUrban** [comment]
This has been fixed with the latest commit, thanks.

**Comment by JakeUrban** [comment]
https://github.com/stellar/django-polaris/commit/7195943be443d8ea990fe9d113df9bfb15035c41
