### ISSUE TITLE
Handle 504 error more gracefully 

### ISSUE THREAD

**Issue by Zagan202** [stellar/django-polaris#361]
### What version are you using?

v1.1.5

### What did you do?

Submitting a transaction while the network is congested.

### What did you expect to see?
`submit_stellar_deposit` handle this error more gracefully 

### What did you see instead?

Request failed with status code 504
`submit_stellar_deposit`
```
2020-12-15 18:09:47,566 - INFO: polaris.utils: BadResponseError
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/polaris/polaris/management/commands/poll_pending_deposits.py", line 228, in handle
    self.execute_deposits()
  File "/code/polaris/polaris/management/commands/poll_pending_deposits.py", line 311, in execute_deposits
    cls.execute_deposit(transaction)
  File "/code/polaris/polaris/management/commands/poll_pending_deposits.py", line 326, in execute_deposit
    success = execute_deposit(transaction)
  File "/code/polaris/polaris/management/commands/poll_pending_deposits.py", line 53, in execute_deposit
    return create_stellar_deposit(transaction)
  File "/code/polaris/polaris/utils.py", line 196, in create_stellar_deposit
    return submit_stellar_deposit(transaction, multisig=multisig)
  File "/code/polaris/polaris/utils.py", line 248, in submit_stellar_deposit
    tx_result = TransactionResult.from_xdr(e.result_xdr)
  File "/usr/local/lib/python3.7/site-packages/stellar_sdk/xdr/StellarXDR_type.py", line 4395, in from_xdr
    xdr_decoded = base64.b64decode(xdr)
  File "/usr/local/lib/python3.7/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/local/lib/python3.7/base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

**Comment by JakeUrban** [comment]
Yea we should definitely handle this. The easiest way is to offer a larger fee so our transaction gets prioritized. Another solution is to resubmit on 504 responses. We should probably do both.

**Comment by Zagan202** [comment]
Note: Transactions that fail via 504 are in limbo because their status is still set at `pending_stellar`
If this fails in `submit_stellar_deposit`
```
logger.info(e.__class__.__name__)
tx_result = TransactionResult.from_xdr(e.result_xdr)
op_results = tx_result.result.results
```
Then we should at the very least set the status to error
`transaction.status = Transaction.STATUS.error`

**Comment by JakeUrban** [comment]
It definitely goes to the `error` status, it doesn't stay in `pending_stellar`: https://github.com/stellar/django-polaris/blob/99b83e8876a758b3a6113e949521e97d41573165/polaris/polaris/utils.py#L167
