### ISSUE TITLE
Polaris v2: Error when running migrate for the first time

### ISSUE THREAD

**Issue by yuriescl** [stellar/django-polaris#501]
Got an error when running migrate on a new clean project:

```
(polaris) [yuri@kml polaris]$ python manage.py migrate
polaris.sep24.utils: Polaris is in local mode. This makes the SEP-24 interactive flow insecure and should only be used for local development.
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, polaris, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying polaris.0001_initial... OK
  Applying polaris.0002_auto_20200921_2135... OK
  Applying polaris.0003_auto_20201009_1300... OK
  Applying polaris.0004_auto_20201120_1541... OK
  Applying polaris.0005_auto_20210226_0053... OK
  Applying polaris.0006_transaction_more_info_url...Traceback (most recent call last):
  File "/home/yuri/server/server/server/manage.py", line 22, in <module>
    main()
  File "/home/yuri/server/server/server/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/polaris/migrations/0006_transaction_more_info_url.py", line 15, in populate_more_info_urls
    models.Value(f"{settings.HOST_URL}{reverse('more_info')}?id="),
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/yuri/.virtualenvs/server/lib/python3.9/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'more_info' not found. 'more_info' is not a valid view function or pattern name.
```
`pip freeze`:
```
aiohttp==3.7.4.post0
aiohttp-sse-client==0.2.1
asgiref==3.4.1
async-timeout==3.0.1
attrs==21.2.0
black==21.8b0
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.4
click==8.0.1
cryptography==3.4.8
Django==3.2.6
django-cors-headers==3.8.0
django-environ==0.5.0
django-model-utils==4.1.1
django-polaris @ git+https://github.com/stellar/django-polaris.git@5cdda7434281988deb761b34f574dfcaf7ae9f5d
djangorestframework==3.12.4
idna==3.2
mnemonic==0.20
multidict==5.1.0
mypy-extensions==0.4.3
pathspec==0.9.0
platformdirs==2.2.0
pycparser==2.20
PyJWT==2.1.0
PyNaCl==1.4.0
pytz==2021.1
regex==2021.8.28
requests==2.26.0
six==1.16.0
sqlparse==0.4.1
stellar-base-sseclient==0.0.21
stellar-sdk==4.1.1
toml==0.10.2
tomli==1.2.1
typing-extensions==3.10.0.0
urllib3==1.26.6
whitenoise==5.3.0
yarl==1.6.3
```

**Comment by JakeUrban** [comment]
Hey @yuriescl a quick fix may be to add `polaris.urls` to your app's `urlpatterns` in `urls.py`. But that shouldn't be required so I'll adjust the migration file.

**Comment by yuriescl** [comment]
thanks!
